apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb-chart.fullname" . }}
spec:
  selector:
    app: mongo-express
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: {{ .Values.service.nodePort }}
